import hashlib, json
from pathlib import Path
R=Path(__file__).parent
def a(n):
 p=R/n; return {'status':'present','path':n,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'reason':None}
def na(r): return {'status':'not-applicable','path':None,'sha256':None,'reason':r}
keys=['artifact_paths_and_hashes','revision_section_matches_manifest','revision_history_consistency','current_revision_is_latest','unresolved_migrations_resolved','paper_revision_ids_match_manifests','selected_count_matches_papers','paper_identity_uniqueness','agent_task_identity_uniqueness','paper_manifests_match_entries','terminology_symbol_section_consistency','canonical_term_sources_valid','paper_glossaries_reconciled','design_rationale_entries_match_paper_manifests','design_rationale_core_design_coverage','dispatch_records_match_entries','visual_totals_match_papers_and_inventory','checklist_manifest_consistency']
checks={k:k in {'artifact_paths_and_hashes','revision_section_matches_manifest','revision_history_consistency','current_revision_is_latest','unresolved_migrations_resolved','selected_count_matches_papers','paper_identity_uniqueness','agent_task_identity_uniqueness','terminology_symbol_section_consistency','visual_totals_match_papers_and_inventory','checklist_manifest_consistency'} for k in keys}
arts={k:a(v) for k,v in {'execution_checklist':'execution_checklist.md','search_log':'search_log.md','github_sources':'github_sources.md','impact_signals':'impact_signals.md','paper_db':'paper_db.jsonl','selection':'selection.md','agent_dispatch_log':'agent_dispatch_log.md','figure_inventory':'figure_inventory.md','contact_sheet':'contact-sheet.png','synthesis':'synthesis.md'}.items()}; arts['generated_diagram']=na('Required responses-doc path unavailable; no substitute generated.')
m={'schema_version':'1.3.0','deliverable_type':'ai-algorithm-survey','field':{'slug':'multimodal-sparse-attention-trends','display_name':'Multimodal Sparse Attention Top-Venue Trends','search_date':'2026-07-23','target_paper_count':38,'selected_paper_count':0},'completion_status':'blocked','revision_info':{'document_path':'synthesis.md','section_heading':'Revision information','current_version':'1.0.0','current_revision_id':'rev-2026-07-23-initial','history':[{'revision_id':'rev-2026-07-23-initial','version':'1.0.0','revised_at':'2026-07-23T12:00:00+08:00','revised_by':'Codex','revision_type':'initial','supersedes':None,'migration_resolution':None,'summary':'Initial audited trend corpus and survey integration.','reason':'Requested top-venue trend and affiliation analysis.','affected_locations':['synthesis.md','paper_db.jsonl'],'evidence':['paper_db.jsonl','venue_counts.csv','organization_counts.csv'],'impact_on_conclusions':'material'}]},'schema_validation':{'status':'passed','validator':'jsonschema Draft202012Validator','errors':[]},'semantic_validation':{'status':'blocked','validator':'manual reduced-scope audit','checks':checks,'errors':['Per-paper manifests and isolated deep reviews were skipped by request.','Affiliations are directly verified for 6 of 38 formal papers.']},'search_coverage':{'general_search':'passed','github_or_awesome':'skipped-with-reason','arxiv':'passed','top_venues':'passed','impact_signals':'skipped-with-reason','affiliations':'blocked'},'agent_isolation':{'mode':'reduced-user-accepted','all_papers_fresh_agent':False,'provenance_verified':False,'external_integrity_verified':False,'user_accepted_reduced_standard':True},'artifacts':arts,'papers':[],'terminology_and_symbols':{'document_path':'synthesis.md','section_heading':'Terminology and symbols','terms':[],'symbol_applicability':'not-applicable','symbols':[],'coverage':{'key_terms':'blocked','key_symbols':'not-applicable','paper_specific_differences':'skipped-with-reason','ambiguities':'passed'}},'synthesis_coverage':{'timeline':True,'taxonomy':True,'lineage':False,'comparison':True,'terminology_and_symbols':True,'design_rationales':False,'infrastructure':True,'trends':True,'evidence_caveats':True},'visual_qa':{'counted_total':2,'inventory_fields_complete':True,'contact_sheet_qa':'passed','individual_crop_qa':'passed','no_crop_reason':None},'presentation':{'requested':False,'deck':na('No presentation requested.'),'rendered_qa':'not-applicable'},'limitations':[{'requirement':'Isolated per-paper deep reviews','status':'skipped-with-reason','reason':'User requested trend analysis without new deep reviews.','effect_on_conclusions':'Counts are an audited lower bound.'},{'requirement':'Complete affiliation verification','status':'blocked','reason':'Only 6 of 38 formal papers have directly verified affiliations.','effect_on_conclusions':'Organization results are a verified subset, not a ranking.'}]}
(R/'deliverable_manifest.json').write_text(json.dumps(m,indent=2)+'\n')
